version: "3.8"

services:
     archer_ai:
          container_name: archer_ai # Set the container name
          image: archer_ai:v1
          ports:
               - "5000:5000" # Map port from the container to the host
          volumes:
               - archer_ai_data:/mnt/share/ # Persist MySQL data
          restart: unless-stopped # Restart policy

volumes:
     mysql_data:
