version: "3.8"

services:
     ollama:
          container_name: ollama
          image: ollama/ollama
          volumes:
               - ollama_data:/root/.ollama
          command: serve
          entrypoint: /bin/ollama
          restart: unless-stopped
          deploy:
               resources:
                    reservations:
                         devices:
                              - capabilities: ["gpu"]
          runtime: nvidia
     reggie:
          container_name: reggie
          image: python
          volumes:
            - python_data:/mnt/share/
          restart: unless-stopped


volumes:
     ollama_data:
     python_data:
